### ISSUE TITLE
Infinite-Loop Problem

### ISSUE THREAD

**Issue by mdoyle179** [mdoyle179/BigGameCats#3]

**Comment by drock1993ad** [comment]
Sometime, when you run, we get an infinite-loop and no player will win.  Right now the code uses a built in shuffle method from Collections:  https://www.tutorialspoint.com/java/util/collections_shuffle.htm  https://stackoverflow.com/questions/2249520/javas-collections-shuffle-is-doing-what

Collections.shuffle(deck, new Random(System.nanoTime()));

I think we might have to create or find a shuffling algorithm so that someone wins no matter how the cards are shuffled.

**Comment by OCrypter** [comment]
Hi, i have modified the code to return the hands on each team. the infinite look looks like a sweet spot where both players are alternating the win with equal number of cards. Check the attached log
[Cards_Infinite_loop.txt](https://github.com/mdoyle179/BigGameCats/files/1357133/Cards_Infinite_loop.txt)

**Comment by cheziral** [comment]
issue resolved
